services:
  # Base de datos PostgreSQL
  - type: pserv
    name: minegocio-db
    env: postgresql
    plan: free

  # Backend Spring Boot con Docker
  - type: web
    name: minegocio-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: minegocio-db
          property: connectionString
      - key: MINE_NEGOCIO_APP_JWT_SECRET
        generateValue: true
      - key: MINE_NEGOCIO_APP_FRONTEND_URL
        value: https://negocio360.org

  # Frontend React (Static Site)
  - type: web
    name: negocio360-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://minegocio-backend.onrender.com/api 