-- Script para agregar la columna eliminado a la tabla detalle_conteo
-- Ejecutar este script en la consola H2

-- Verificar si la columna ya existe
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DETALLE_CONTEO' 
AND COLUMN_NAME = 'ELIMINADO';

-- Si no existe, agregarla
ALTER TABLE DETALLE_CONTEO ADD COLUMN ELIMINADO BOOLEAN NOT NULL DEFAULT FALSE;

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS IDX_DETALLE_CONTEO_ELIMINADO ON DETALLE_CONTEO(ELIMINADO);
CREATE INDEX IF NOT EXISTS IDX_DETALLE_CONTEO_SECTOR_ELIMINADO ON DETALLE_CONTEO(CONTEO_SECTOR_ID, ELIMINADO);

-- Verificar que la columna se agregó correctamente
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DETALLE_CONTEO' 
AND COLUMN_NAME = 'ELIMINADO';











